### ISSUE TITLE
Incidence

### ISSUE THREAD

**Issue by T0nete** [desperfectosweb/back#8]
This task will work as an Epic that contains all the new features to implement to the incidences. Each of the following tasks will have associate one issue.

- [x]  [Report new incidence ](https://github.com/desperfectosweb/back/issues/9 )
- [x] [Get incidences](https://github.com/desperfectosweb/back/issues/10)
- [x] [Get incidence detail](https://github.com/desperfectosweb/back/issues/11)
- [x] [Update incidence](https://github.com/desperfectosweb/back/issues/12)
- [x] [Delete incidence](https://github.com/desperfectosweb/back/issues/13)
- [ ] [Get incidences by filters](https://github.com/desperfectosweb/back/issues/14)
